### PR TITLE
Fix: Wheezy expired key in debian-archive-keyring.gpg causes simple-cdd to fail

### PR DESCRIPTION
**Pull request by honzahommer**

### CODE REVIEW

**Comment by ssinyagin** [comment]
there's no backslash after  build-simple-cdd in your version, so it breaks the functionality. Please fix and test again.

**Comment by honzahommer** [comment]
> there's no backslash after build-simple-cdd in your version, so it breaks the functionality. Please fix and test again.

Fixed, my mistake, sorry :-(

**Comment by ssinyagin** [comment]
but did you actually test it? And why wheezy?

**Comment by honzahommer** [comment]
> but did you actually test it? And why wheezy?

Yes, i test it. Whole problem is with expired Wheeze release key.

```
root @ bebe-cap-net-cz in /home/honza
$ gpg --no-default-keyring --keyring=/usr/share/keyrings/debian-archive-keyring.gpg --list-keys
/usr/share/keyrings/debian-archive-keyring.gpg
----------------------------------------------
pub   rsa4096 2012-05-08 [SC] [expired: 2019-05-07]
      ED6D65271AACF0FF15D123036FB2A1C265FFB764
uid           [ expired] Wheezy Stable Release Key <debian-release@lists.debian.org>
```

simple-ccd check if all keys in keychain are not expired and valid, in this case build fails...

```
$ ./build apu64
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
2019-05-16 18:01:42,087 ERROR reprepro: updating package lists exited with code 255
2019-05-16 18:01:42,087 ERROR Last 3 lines of standard error:
2019-05-16 18:01:42,088 ERROR reprepro: updating package lists: VerifyRelease condition '6FB2A1C265FFB764|8B48AD6246925553|CBF8D6FD518E17E1|7638D0442B90D010|9D6D8F6BC857C906|EF0F382A1A7B6500|E0B11894F66AEC98|04EE7237B7D453EC|EDA0D2388AE22BA9|AA8E81B4331F7F50' lists expired key '6FB2A1C265FFB764'.
2019-05-16 18:01:42,088 ERROR reprepro: updating package lists: (To use it anyway, append it with a '!' to force usage).
2019-05-16 18:01:42,088 ERROR reprepro: updating package lists: There have been errors!
2019-05-16 18:01:42,089 ERROR reprepro failed with exit code: 255
ERROR: Job failed: exit code 1
```

Solution is simple, remove expired key from keychain and this keychain pass to simple-ccd.

```
$ ./build apu64
OK
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
/builds/honza/pcengines-apu-debian-cd/images/debian-9.8-amd64-CD-1.iso
Uploading artifacts...
images/*: found 2 matching files                   
Uploading artifacts to coordinator... ok            id=738 responseStatus=201 Created token=u7vWvr5Q
Job succeeded
```

**Comment by ssinyagin** [comment]
I see, I'll give it a test

**Review by ssinyagin — CHANGES_REQUESTED** [review]
no, this will definitely not go in the main branch. It's totally insecure because root password is specified in clear text. You can still keep your own branch with these changes.

Sorry for delays, my work was totally unrelated to pcengines in the past 18 months

**Pull request closed without merging**
