### PR TITLE
Change to an LVM with /boot /home and / partition.

### PR DESCRIPTION
**Pull request by micressor**
As discussed in issue #9. I have tested the apu64.conf profile with distribution jessie.

### CODE REVIEW

**Comment by ssinyagin** [comment]
hi, but why /home, and not /var? Who needs a user home partition on a small server?

**Comment by ssinyagin** [comment]
but in general, it looks like it needs a templating engine, so that the user could choose various options before creating an ISO image. Can you propose something?

**Comment by micressor** [comment]
You're right, `/var` makes more sense. Or may be `/srv`?

I think the preseed already very good. You should not be able to configure too much. For my needs it is enough with LVM and the separate `/var` partition.

If you want, I can add (and test) a commit that will change the partition from `/home` to `/var`.

**Comment by ssinyagin** [comment]
let's make /var in a separate partition, and the I'll think about a templating engine. I'm also not comfortable with habing to maintain the 32bit version, so the templating engine would solve that too. Also simple-cdd is undergoing some serious changes, so we need to do something nice here.

**Comment by micressor** [comment]
I have successfully tested the installation on an APU2 with apu64.conf and jessie.

**Comment by ssinyagin** [comment]
I think I will drop the 32-bit version, in order to simplify the maintenance. Who needs it anyway

**Comment by ssinyagin** [comment]
reverted your commit, now back to how it was.

**Comment by ssinyagin** [comment]
by the way, you also need to change the value of issue_discards option from 0 to 1 in /etc/lvm/lvm.conf

**Pull request merged**
