### PR TITLE
Use httpredir.debian.org as mirror, http.debian.net is deprecated

### PR DESCRIPTION
**Pull request by waja**

### CODE REVIEW

**Comment by ssinyagin** [comment]
did you test it for both architectures?

**Comment by waja** [comment]
I was able to create jessie images for both archs:

```
-rw-r--r-- 1 root root 161480704 Sep 13 12:24 debian-8.5-amd64-CD-1.iso
-rw-r--r-- 1 root root      4431 Sep 13 12:24 debian-8.5-amd64-CD-1.list.gz
-rw-r--r-- 1 root root 171966464 Sep 13 12:30 debian-8.5-i386-CD-1.iso
-rw-r--r-- 1 root root      4552 Sep 13 12:30 debian-8.5-i386-CD-1.list.gz
```

**Comment by ssinyagin** [comment]
can you please test the installation and work of the resulted image?

**Comment by waja** [comment]
I'll have to wait until my ordered SSD arrives. But yes I'll test it. For now I was just able to test it to the point where the partitioning happens in the installer. :)

**Comment by waja** [comment]
It worked like a charm for both arch. :+1:

**Comment by waja** [comment]
Many thanks for the merge and providing such a nice peace of code.

**Comment by ssinyagin** [comment]
maybe you have time to address this issue? https://github.com/ssinyagin/pcengines-apu-debian-cd/issues/9

**Comment by waja** [comment]
Puhhhh... That's too far out of my scope/interest. I just needed to deploy one machine. :)

**Pull request merged**
